project:
  type: website
  output-dir: docs
  
website:
  title: "Dataolo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter-x
        href: https://twitter.com/
      - icon: github
        href: https://github.com/paochevalier/website_pro_github
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true

editor: source

